services:
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=notification_service'
      - 'POSTGRES_PASSWORD=password'

  auth:
    build: .
    command: java -jar app.jar
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - database