spring:

  mail:
    host: ${EMAIL_SENDER_HOST}
    port: ${EMAIL_SENDER_PORT}
    username: ${EMAIL_SENDER_ID}
    password: ${EMAIL_SENDER_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT}

