spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    show-sql: true

server:
  port: ${SERVER_PORT}
  host: http://localhost:${SERVER_PORT}

jwt:
  jwtSecret: ${SECRET_WORD}
  expirationConfirmTime: ${EXPIRATION_CONFIRM}
  expirationUserTime: ${EXPIRATION_USER_TIME}
  issuer: ${ISSUER}
  subject: ${SUBJECT}
  claimName: ${CLAIM_NAME}

urls:
  userApiCreatePerson: ${USER_API_CREATE_PERSON}
  userApiGetPerson: ${USER_API_GET_PERSON}
  appUrl: ${APP_URL}
  mailServiceUrl: ${MAIL_SERVICE_URL}
  userApiDeletePerson: ${USER_API_DELETE_PERSON}


